name: Deploy Django to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repo
    - name: Checkout repo
      uses: actions/checkout@v4

    # Step 2: Set up Python 3.12
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Log in to Azure
    - name: Log in via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
            python -m venv antenv
            source antenv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
    - name: Run migrations
      run: |
        source antenv/bin/activate
        python manage.py migrate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: quiz-system-alwp.azurewebsites.net


    - name: Collect static files
      run: python manage.py collectstatic --noinput
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: quiz-system-alwp.azurewebsites.net
        STATIC_ROOT: ./static
        MEDIA_ROOT: ./media

    # Step 6: Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: quiz-system-alwp
        package: .
        slot-name: production
